name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm init -y
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Prepare web assets
        run: |
          mkdir -p www
          cp index.html www/
          cp script.js www/
          cp style.css www/

      - name: Init Capacitor
        run: npx cap init "SkyWatch" "com.skywatch.app" --web-dir=www

      - name: Add Android platform
        run: npx cap add android

      - name: Copy web assets
        run: npx cap copy

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SkyWatch-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
