name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Setup Java & Android SDK
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install @capacitor/core @capacitor/cli @capacitor/android --save

      # 5. Init Capacitor (point web-dir to root instead of www)
      - name: Init Capacitor
        run: |
          if [ ! -f capacitor.config.json ]; then
            npx cap init "SkyWatch" "com.skywatch.app" --web-dir=.
          fi

      # 6. Add Android platform (only first time)
      - name: Add Android platform
        run: |
          if [ ! -d android ]; then
            npx cap add android
          fi

      # 7. Sync Capacitor (this generates capacitor.settings.gradle)
      - name: Sync Capacitor
        run: npx cap sync android

      # 8. Build Android APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      # 9. Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: SkyWatch-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
